[database]
host = {{ env "DB_HOST" }}
port = {{ env "DB_PORT" }}
database = {{ env "DB_NAME" }}
user = {{ env "DB_USER" }}
password = {{ env "DB_PASSWORD" }}
sslmode = {{ if eq (env "DB_SSL_ENABLED") "true" }}require{{ else }}disable{{ end }}
