// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package openapi

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status string `json:"status"`
}

// Journey defines model for Journey.
type Journey struct {
	Location  string `json:"location"`
	Name      string `json:"name"`
	Thumbnail string `json:"thumbnail"`
	Timestamp string `json:"timestamp"`
}

// JourneysResponse defines model for JourneysResponse.
type JourneysResponse = []Journey
