// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package openapi

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status string `json:"status"`
}
